name: Deploy to Fly

on:
  push:
    branches:
      - "main"

jobs:
  deploy:
    name: Deploy with Wasp
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install Wasp
        run: curl -sSL https://get.wasp-lang.dev/installer.sh | sh
      - uses: superfly/flyctl-actions/setup-flyctl@master
      - run: wasp deploy fly deploy
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_TOKEN }}