name: Deploy to Fly

on: [push]

jobs:
  deploy:
    name: Deploy proxy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: superfly/flyctl-actions/setup-flyctl@master
      - run: flyctl apps list
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_TOKEN }}